apply plugin: 'com.android.application'

def COMPILE_SDK = 37
def MIN_SDK     = 21
def TARGET_SDK  = 37

android {
    namespace 'com.xiaoyumi.biliweb'
    compileSdk COMPILE_SDK

    defaultConfig {
        applicationId "com.xiaoyumi.biliweb"
        minSdk MIN_SDK
        targetSdk TARGET_SDK
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
        checkTestSources false
        checkDependencies false
    }
}

dependencies {
}
//./gradlew lint -PenableLint
if (!project.hasProperty("enableLint")) {
    tasks.matching { it.name.startsWith("lint") }.configureEach {
        enabled = false
    }
}
